# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national', '0002_constituencyurl_privatekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatekey',
            name='key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
